site_name: Arm CMSIS Debuger
repo_name: GitHub
repo_url: https://github.com/Open-CMSIS-Pack/vscode-cmsis-debugger/
edit_uri: edit/main/docs/
nav:
    - Home: index.md
    - Setup: setup.md
    - Create launch configuration: configure.md
    - Start debugging: debug.md
    - Debug views: debug_views.md
theme:
  name: readthedocs
markdown_extensions:
  - admonition
extra_css:
  - css/extra.css
use_directory_urls: false
