name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  merge_group:

jobs:
  build:
    name: Build, test, and package
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 20.x
          registry-url: https://npm.pkg.github.com
          always-auth: true
      - name: Build
        env:
          GITHUB_TOKEN: ${{github.token}}
        run: yarn --immutable
      - name: Test
        run: yarn test
      - name: Package desktop
        run: |
          yarn package
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
        with:
          name: vsix-package
          path: ./*.vsix
          retention-days: 1
